services:
  postgres:
    image: postgres:16-alpine
    container_name: hospy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medico_db
      POSTGRES_USER: medico_user
      POSTGRES_PASSWORD: Hospy2024!
    ports:
      - "5432:5432"
    volumes:
      - hospy_pgdata:/var/lib/postgresql/data
      - ./database/init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medico_user -d medico_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  hospy_pgdata:
